version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: ocg-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ee123456
      MYSQL_DATABASE: OCGtradingSystem
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - ocg-network

  # OCG交易系统应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocg-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/OCGtradingSystem?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ee123456
    networks:
      - ocg-network

networks:
  ocg-network:
    driver: bridge

volumes:
  mysql-data: